config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	mount Sidekiq::Web => '/sidekiq'

	root 'object_states#index'

	resources :object_states, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/object_state.rb
class ObjectState < ApplicationRecord

  validates :object_id, :object_type, :timestamp, presence: true

  serialize :object_changes, JSON

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/object_states_controller.rb
class ObjectStatesController < ApplicationController

  before_action :prepare_search_form, only: [:index]

  def index; end

  def new; end

  def create
    ObjectStateForm.new(object_state_params).save
    redirect_to object_states_path
  end

  private

  def object_state_params
    params.require(:file_upload).permit(:csv)
  end

  def prepare_search_form
    search_params = params[:search_form].present? ? params[:search_form].permit(:object_id, :object_type, :timestamp) : {}
    @search_form = SearchForm.new(search_params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[type.to_sym] || type.to_s
  end

end

app/helpers/object_states_helper.rb
module ObjectStatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_flash_message.html.slim
- flash.each do |key, value|
  .alert class="#{flash_class(key)}"
    .container

      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true" &times;

      = value

app/views/application/_modal.html.slim
#modal-form.modal.fade aria-hidden="true" role="dialog" tabindex="-1" data-backdrop="static" data-keyboard="false"
  .modal-dialog

    .modal-content

      .modal-header

        h2 Replace this text
        button.close aria-hidden="true" data-dismiss="modal" type="button" &times;

      .modal-body

      .modal-footer.hide

app/views/layouts/application.html.slim
doctype html
html
    head
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta charset="utf-8"
    meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport"

    title Object State Reconstruction

    = stylesheet_link_tag :application, 'data-turbolinks-track': true
    = csrf_meta_tags

    body

      .container

        #flash_message
          = render partial: 'flash_message'

        = yield

        = render partial: 'modal'

    = javascript_include_tag :application, 'data-turbolinks-track': true

app/views/object_states/_new.html.slim
.modal-header
  h4 Import Object State CSV

= simple_form_for :file_upload, url: object_states_path, method: :post do |f|
  .modal-body
    = f.input :csv, as: :file, label: 'CSV File'

  .modal-footer
    = link_to 'Cancel', '#', class: 'btn btn-default pull-left', data: { dismiss: 'modal' }
    = f.submit 'Import', class: 'btn btn-primary'

app/views/object_states/index.html.slim
h1 Object State Reconstruction

/ Panel for search form
.panel.panel-default
  .panel-heading
    .row
      .col-md-6
        h4 Search Object States
      .col-md-6
        = link_to 'Import CSV', new_object_state_path, remote: true, class: 'btn btn-primary pull-right'

  = simple_form_for @search_form, as: :search_form, url: object_states_path, method: :get do |f|
    .panel.body.search-form
      .row
        .col-md-4
          = f.input :object_id, collection: @search_form.object_id_options, label: 'Object ID', include_blank: false

        .col-md-4
          = f.input :object_type, collection: @search_form.object_type_options, include_blank: false

        .col-md-4
          = f.input :timestamp, input_html: { required: true }

    .panel-footer
      .row
        .col-md-12
          = f.submit 'Search', class: 'btn btn-default pull-right'

/ Panel for displaying object states results
.panel.panel-default
  .panel-heading
    .row
      .col-md-6
        h3 Result

  .panel-body
    - if params[:search_form].present?
      p = "Object ID: #{@search_form.object_id}"
      p = "Object Type: #{@search_form.object_type}"
      p = "Timestamp: #{@search_form.timestamp}"
      p Object Changes Logs:
      table.table.table-bordered
        thead
          tr
            th Timestamp
            th Object Changes
        tbody
          - @search_form.search_result.each do |obj|
            tr
              td = obj.timestamp
              td = obj.object_changes
      hr
      p Current Object Changes at #{@search_form.timestamp}:
      h4 = @search_form.object_changes

app/views/object_states/new.js.erb
$('#modal-form .modal-content').html("<%= j render(partial: 'new')%>")
$('#modal-form').modal('show')

app/views/pages/index.html.slim
h1 Object State Reconstruction

.panel.panel-default
	.panel-heading
		h3 Upload a CSV File

	= simple_form_for :file_upload, url: pages_path, method: :post do |f|
		.panel-body

			= f.input :csv_upload, as: :file

		.panel-footer
			= f.submit 'Save', class: 'btn btn-default'